# Importation des dépendances

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import cluster
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression 
from sklearn.ensemble import StackingClassifier #combinaison des classifieurs
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split

# Importation du dataset

In [2]:
data = pd.read_csv(r"C:\Users\tjwri\Downloads\Credit-card-approval-prediction-classification-main\datasets\application_record.csv", index_col=0)
data

CODE_GENDER FLAG_OWN_CAR FLAG_OWN_REALTY  CNT_CHILDREN  \
ID                                                               
5008804           M            Y               Y             0   
5008805           M            Y               Y             0   
5008806           M            Y               Y             0   
5008808           F            N               Y             0   
5008809           F            N               Y             0   
...             ...          ...             ...           ...   
6840104           M            N               Y             0   
6840222           F            N               N             0   
6841878           F            N               N             0   
6842765           F            N               Y             0   
6842885           F            N               Y             0   

         AMT_INCOME_TOTAL      NAME_INCOME_TYPE  \
ID                                                
5008804          427500.0               Working   
5008805          427500.0               Working   
5008806          112500.0               Working   
5008808          270000.0  Commercial associate   
5008809          270000.0  Commercial associate   
...                   ...                   ...   
6840104          135000.0             Pensioner   
6840222          103500.0               Working   
6841878           54000.0  Commercial associate   
6842765           72000.0             Pensioner   
6842885          121500.0               Working   

                   NAME_EDUCATION_TYPE    NAME_FAMILY_STATUS  \
ID                                                             
5008804               Higher education        Civil marriage   
5008805               Higher education        Civil marriage   
5008806  Secondary / secondary special               Married   
5008808  Secondary / secondary special  Single / not married   
5008809  Secondary / secondary special  Single / not married   
...                                ...                   ...   
6840104  Secondary / secondary special             Separated   
6840222  Secondary / secondary special  Single / not married   
6841878               Higher education  Single / not married   
6842765  Secondary / secondary special               Married   
6842885  Secondary / secondary special               Married   

         NAME_HOUSING_TYPE  DAYS_BIRTH  DAYS_EMPLOYED  FLAG_MOBIL  \
ID                                                                  
5008804   Rented apartment      -12005          -4542           1   
5008805   Rented apartment      -12005          -4542           1   
5008806  House / apartment      -21474          -1134           1   
5008808  House / apartment      -19110          -3051           1   
5008809  House / apartment      -19110          -3051           1   
...                    ...         ...            ...         ...   
6840104  House / apartment      -22717         365243           1   
6840222  House / apartment      -15939          -3007           1   
6841878       With parents       -8169           -372           1   
6842765  House / apartment      -21673         365243           1   
6842885  House / apartment      -18858          -1201           1   

         FLAG_WORK_PHONE  FLAG_PHONE  FLAG_EMAIL OCCUPATION_TYPE  \
ID                                                                 
5008804                1           0           0             NaN   
5008805                1           0           0             NaN   
5008806                0           0           0  Security staff   
5008808                0           1           1     Sales staff   
5008809                0           1           1     Sales staff   
...                  ...         ...         ...             ...   
6840104                0           0           0             NaN   
6840222                0           0           0        Laborers   
6841878                1           0           0     Sales staff   
684276

# nettoyage du dataset

In [3]:
data['CODE_GENDER'].replace(['M','F'],[0,1], inplace=True)
data["FLAG_OWN_REALTY"].replace(['N','Y'],[0,1], inplace=True)
data["FLAG_OWN_CAR"].replace(['N','Y'],[0,1], inplace=True)
data["NAME_INCOME_TYPE"].replace(['Pensioner','Working','Commercial associate','State servant','Student'],[0,1,2,3,4], inplace=True)
data["NAME_EDUCATION_TYPE"].replace(['Secondary / secondary special','Higher education', 'Lower secondary','Incomplete higher','Academic degree'],[0,1,2,3,4], inplace=True)
data["NAME_FAMILY_STATUS"].replace(['Married','Civil marriage','Separated','Single / not married','Widow'],[0,1,2,3,4], inplace=True)
data["NAME_HOUSING_TYPE"].replace(['House / apartment','Rented apartment','Office apartment','Municipal apartment','Co-op apartment','With parents'],[0,1,2,3,4,5], inplace=True)
data =data.drop(['OCCUPATION_TYPE'],axis= 1)

# Création du model pour avoir les sorties

In [8]:
model_kmeans=cluster.KMeans(n_clusters=2)

In [9]:
Results=model_kmeans.fit_predict(data)
Results

array([0, 0, 0, ..., 0, 1, 0])

In [12]:
data["Resultats"]=Results

In [13]:
# data.to_csv('DatasetTreated')
data

CODE_GENDER  FLAG_OWN_CAR  FLAG_OWN_REALTY  CNT_CHILDREN  \
ID                                                                  
5008804            0             1                1             0   
5008805            0             1                1             0   
5008806            0             1                1             0   
5008808            1             0                1             0   
5008809            1             0                1             0   
...              ...           ...              ...           ...   
6840104            0             0                1             0   
6840222            1             0                0             0   
6841878            1             0                0             0   
6842765            1             0                1             0   
6842885            1             0                1             0   

         AMT_INCOME_TOTAL  NAME_INCOME_TYPE  NAME_EDUCATION_TYPE  \
ID                                                                 
5008804          427500.0                 1                    1   
5008805          427500.0                 1                    1   
5008806          112500.0                 1                    0   
5008808          270000.0                 2                    0   
5008809          270000.0                 2                    0   
...                   ...               ...                  ...   
6840104          135000.0                 0                    0   
6840222          103500.0                 1                    0   
6841878           54000.0                 2                    1   
6842765           72000.0                 0                    0   
6842885          121500.0                 1                    0   

         NAME_FAMILY_STATUS  NAME_HOUSING_TYPE  DAYS_BIRTH  DAYS_EMPLOYED  \
ID                                                                          
5008804                   1                  1      -12005          -4542   
5008805                   1                  1      -12005          -4542   
5008806                   0                  0      -21474          -1134   
5008808                   3                  0      -19110          -3051   
5008809                   3                  0      -19110          -3051   
...                     ...                ...         ...            ...   
6840104                   2                  0      -22717         365243   
6840222                   3                  0      -15939          -3007   
6841878                   3                  5       -8169           -372   
6842765                   0                  0      -21673         365243   
6842885                   0                  0      -18858          -1201   

         FLAG_MOBIL  FLAG_WORK_PHONE  FLAG_PHONE  FLAG_EMAIL  CNT_FAM_MEMBERS  \
ID                                                                              
5008804           1                1           0           0              2.0   
5008805           1                1           0           0              2.0   
5008806           1                0           0           0              2.0   
5008808           1                0           1           1              1.0   
5008809           1                0           1           1              1.0   
...             ...              ...         ...         ...              ...   
6840104           1                0           0           0              1.0   
6840222           1                0           0           0              1.0   
6841878           1                1           0           0              1.0   
6842765           1                0           0           0              2.0   
6842885           1                0           1           0              2.0   

         Resultats  
ID                  
5008804          0  
5008805          0  
5008806          0  
5008808          0  
5008809          0  
...            ...  
68

In [14]:
Y=data["Resultats"]
X=data.drop(["Resultats"], axis=1)
X

CODE_GENDER  FLAG_OWN_CAR  FLAG_OWN_REALTY  CNT_CHILDREN  \
ID                                                                  
5008804            0             1                1             0   
5008805            0             1                1             0   
5008806            0             1                1             0   
5008808            1             0                1             0   
5008809            1             0                1             0   
...              ...           ...              ...           ...   
6840104            0             0                1             0   
6840222            1             0                0             0   
6841878            1             0                0             0   
6842765            1             0                1             0   
6842885            1             0                1             0   

         AMT_INCOME_TOTAL  NAME_INCOME_TYPE  NAME_EDUCATION_TYPE  \
ID                                                                 
5008804          427500.0                 1                    1   
5008805          427500.0                 1                    1   
5008806          112500.0                 1                    0   
5008808          270000.0                 2                    0   
5008809          270000.0                 2                    0   
...                   ...               ...                  ...   
6840104          135000.0                 0                    0   
6840222          103500.0                 1                    0   
6841878           54000.0                 2                    1   
6842765           72000.0                 0                    0   
6842885          121500.0                 1                    0   

         NAME_FAMILY_STATUS  NAME_HOUSING_TYPE  DAYS_BIRTH  DAYS_EMPLOYED  \
ID                                                                          
5008804                   1                  1      -12005          -4542   
5008805                   1                  1      -12005          -4542   
5008806                   0                  0      -21474          -1134   
5008808                   3                  0      -19110          -3051   
5008809                   3                  0      -19110          -3051   
...                     ...                ...         ...            ...   
6840104                   2                  0      -22717         365243   
6840222                   3                  0      -15939          -3007   
6841878                   3                  5       -8169           -372   
6842765                   0                  0      -21673         365243   
6842885                   0                  0      -18858          -1201   

         FLAG_MOBIL  FLAG_WORK_PHONE  FLAG_PHONE  FLAG_EMAIL  CNT_FAM_MEMBERS  
ID                                                                             
5008804           1                1           0           0              2.0  
5008805           1                1           0           0              2.0  
5008806           1                0           0           0              2.0  
5008808           1                0           1           1              1.0  
5008809           1                0           1           1              1.0  
...             ...              ...         ...         ...              ...  
6840104           1                0           0           0              1.0  
6840222           1                0           0           0              1.0  
6841878           1                1           0           0              1.0  
6842765           1                0           0           0              2.0  
6842885           1                0           1           0              2.0  

[438557 rows x 16 columns]

# Split The Dataset

In [15]:
X_train, X_test, Y_train, Y_test= train_test_split(X,Y,test_size=0.20,random_state=0)

# Logistic Regression

In [20]:
model_LR= LogisticRegression()

In [21]:
model_LR.fit(X_train,Y_train)

LogisticRegression()

In [22]:
y_train_pred= model_LR.predict(X_test)

In [23]:
model_LR.score(X_test,Y_test)

0.9999885990514411

# Decision Tree

In [25]:
Decision_tree = DecisionTreeClassifier(criterion='entropy')

In [26]:
Decision_tree.fit(X_train,Y_train)

DecisionTreeClassifier(criterion='entropy')

In [27]:
Decision_tree.predict(X_test)

array([0, 0, 0, ..., 0, 0, 0])

In [28]:
Decision_tree.score(X_test,Y_test)

1.0

# Stacked Model

In [36]:
listes_estimateurs = [
    ('dt',Decision_tree),
    ('LR',model_LR) 
]

In [37]:
stack_model = StackingClassifier(
    estimators=listes_estimateurs, final_estimator=RandomForestClassifier()
)

In [38]:
stack_model.fit(X_train, Y_train)

StackingClassifier(estimators=[('dt',
                                DecisionTreeClassifier(criterion='entropy')),
                               ('LR', LogisticRegression())],
                   final_estimator=RandomForestClassifier())

In [39]:
stack_model.predict(X_test)

array([0, 0, 0, ..., 0, 0, 0])

In [40]:
stack_model.score(X_test,Y_test)

1.0